"""DDL and data-load script generation from a confirmed ERD (pure functions)."""

import io
import json
import zipfile
from collections.abc import Callable

from app.modules.exmigrate.schemas import Dialect, Erd, ErdColumn, ErdTable

TYPES: dict[Dialect, dict[str, str]] = {
    "sqlite": {
        "integer": "INTEGER",
        "decimal": "NUMERIC",
        "boolean": "INTEGER",
        "date": "TEXT",
        "datetime": "TEXT",
        "text": "TEXT",
    },
    "postgresql": {
        "integer": "BIGINT",
        "decimal": "NUMERIC",
        "boolean": "BOOLEAN",
        "date": "DATE",
        "datetime": "TIMESTAMP",
        "text": "TEXT",
    },
    "mssql": {
        "integer": "BIGINT",
        "decimal": "DECIMAL(28, 8)",
        "boolean": "BIT",
        "date": "DATE",
        "datetime": "DATETIME2",
        "text": "NVARCHAR(MAX)",
    },
}
MSSQL_KEY_TEXT = "NVARCHAR(450)"


def quote(dialect: Dialect, name: str) -> str:
    if dialect == "mssql":
        return "[" + name.replace("]", "]]") + "]"
    return '"' + name.replace('"', '""') + '"'


def _comment(text: str) -> str:
    return " ".join(text.split())


def _keyed(erd: Erd) -> set[tuple[str, str]]:
    keys = {(t.name, c.name) for t in erd.tables for c in t.columns if c.primary_key}
    for r in erd.relations:
        keys.add((r.from_table, r.from_column))
        keys.add((r.to_table, r.to_column))
    return keys


def _column_type(dialect: Dialect, table: ErdTable, col: ErdColumn, keyed: set[tuple[str, str]]) -> str:
    if dialect == "mssql" and col.type == "text" and (table.name, col.name) in keyed:
        return MSSQL_KEY_TEXT
    return TYPES[dialect][col.type]


def ddl(erd: Erd, dialect: Dialect, source: str) -> str:
    q: Callable[[str], str] = lambda n: quote(dialect, n)  # noqa: E731
    keyed = _keyed(erd)
    unique_targets = {(r.to_table, r.to_column) for r in erd.relations}
    out = [f"-- Generated by FDE Toolbox ExMigrate from {_comment(source)} ({dialect})", ""]
    fks: list[str] = []
    for t in erd.tables:
        lines = []
        pks = [c.name for c in t.columns if c.primary_key]
        for c in t.columns:
            null = "" if c.nullable and not c.primary_key else " NOT NULL"
            lines.append(f"    {q(c.name)} {_column_type(dialect, t, c, keyed)}{null}")
        if pks:
            lines.append(f"    CONSTRAINT {q(f'pk_{t.name}')} PRIMARY KEY ({', '.join(q(p) for p in pks)})")
        for c in t.columns:
            if (t.name, c.name) in unique_targets and pks != [c.name]:
                lines.append(f"    CONSTRAINT {q(f'uq_{t.name}_{c.name}')} UNIQUE ({q(c.name)})")
        if dialect == "sqlite":
            for r in (r for r in erd.relations if r.from_table == t.name):
                lines.append(f"    FOREIGN KEY ({q(r.from_column)}) REFERENCES {q(r.to_table)} ({q(r.to_column)})")
        label = f" -- {_comment(t.label)}" if t.label and t.label != t.name else ""
        out.append(f"CREATE TABLE {q(t.name)} ({label}")
        out.append(",\n".join(lines))
        out.append(");")
        out.append("")
    if dialect != "sqlite":
        for i, r in enumerate(erd.relations, start=1):
            fks.append(
                f"ALTER TABLE {q(r.from_table)} ADD CONSTRAINT {q(f'fk_{r.from_table}_{i}')} "
                f"FOREIGN KEY ({q(r.from_column)}) REFERENCES {q(r.to_table)} ({q(r.to_column)});"
            )
    return "\n".join(out + fks).rstrip() + "\n"


def load_order(erd: Erd) -> list[ErdTable]:
    """Referenced tables first; cycles keep their original order."""
    deps = {
        t.name: {r.to_table for r in erd.relations if r.from_table == t.name and r.to_table != t.name}
        for t in erd.tables
    }
    done: list[str] = []
    pending = [t.name for t in erd.tables]
    while pending:
        ready = [n for n in pending if deps[n] <= set(done)] or pending[:1]
        for n in ready:
            done.append(n)
            pending.remove(n)
    by_name = {t.name: t for t in erd.tables}
    return [by_name[n] for n in done]


def mapping(erd: Erd, source: str) -> dict[str, object]:
    return {
        "source": source,
        "tables": [
            {
                "table": t.name,
                "sheet": t.source_sheet,
                "header_row": t.header_row or 0,
                "columns": [
                    {"name": c.name, "type": c.type, "source_column": c.source_column}
                    for c in t.columns
                    if c.source_column
                ],
            }
            for t in load_order(erd)
            if t.source_sheet
        ],
    }


LOAD_SCRIPT = '''"""Load the workbook into the target database using mapping.json (generated by FDE Toolbox ExMigrate).

Usage:
    pip install openpyxl            # plus psycopg (PostgreSQL) or pyodbc (SQL Server)
    python load.py WORKBOOK.xlsx --dialect sqlite --url target.db
    python load.py WORKBOOK.xlsx --dialect postgresql --url "postgresql://user:pass@host/db"
    python load.py WORKBOOK.xlsx --dialect mssql --url "DRIVER={ODBC Driver 18 for SQL Server};SERVER=...;DATABASE=..."

Create the tables first with schema.sql. Rows whose mapped cells are all empty are skipped.
"""

import argparse
import datetime
import decimal
import json
import pathlib

from openpyxl import load_workbook

MAPPING = json.loads(pathlib.Path(__file__).with_name("mapping.json").read_text(encoding="utf-8"))
BATCH = 500


def connect(dialect, url):
    if dialect == "sqlite":
        import sqlite3

        return sqlite3.connect(url)
    if dialect == "postgresql":
        import psycopg

        return psycopg.connect(url)
    import pyodbc

    return pyodbc.connect(url)


def quote(dialect, name):
    if dialect == "mssql":
        return "[" + name.replace("]", "]]") + "]"
    return '"' + name.replace('"', '""') + '"'


def column_index(letters):
    n = 0
    for ch in letters.upper():
        n = n * 26 + ord(ch) - 64
    return n - 1


def convert(value, kind, dialect):
    if value is None or (isinstance(value, str) and not value.strip()):
        return None
    if kind == "integer":
        return int(value)
    if kind == "decimal":
        return float(value) if dialect == "sqlite" else decimal.Decimal(str(value))
    if kind == "boolean":
        flag = value if isinstance(value, bool) else str(value).strip().lower() in ("1", "true", "y", "yes", "o")
        return int(flag) if dialect == "sqlite" else flag
    if kind in ("date", "datetime"):
        if isinstance(value, datetime.datetime):
            value = value.date() if kind == "date" else value
        return value.isoformat() if dialect == "sqlite" and hasattr(value, "isoformat") else value
    return str(value)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("workbook")
    parser.add_argument("--dialect", choices=["sqlite", "postgresql", "mssql"], required=True)
    parser.add_argument("--url", required=True)
    args = parser.parse_args()
    marker = "%s" if args.dialect == "postgresql" else "?"
    wb = load_workbook(args.workbook, data_only=True, read_only=True)
    conn = connect(args.dialect, args.url)
    try:
        cur = conn.cursor()
        for table in MAPPING["tables"]:
            cols = table["columns"]
            if not cols or table["sheet"] not in wb.sheetnames:
                continue
            idx = [column_index(c["source_column"]) for c in cols]
            names = ", ".join(quote(args.dialect, c["name"]) for c in cols)
            values = ", ".join([marker] * len(cols))
            sql = f"INSERT INTO {quote(args.dialect, table['table'])} ({names}) VALUES ({values})"
            rows, count = [], 0
            for raw in wb[table["sheet"]].iter_rows(min_row=table["header_row"] + 1, values_only=True):
                cells = [raw[i] if i < len(raw) else None for i in idx]
                if all(v is None or (isinstance(v, str) and not v.strip()) for v in cells):
                    continue
                rows.append([convert(v, c["type"], args.dialect) for v, c in zip(cells, cols)])
                if len(rows) >= BATCH:
                    cur.executemany(sql, rows)
                    count, rows = count + len(rows), []
            if rows:
                cur.executemany(sql, rows)
                count += len(rows)
            print(f"{table['table']}: {count} rows")
        conn.commit()
    finally:
        conn.close()


if __name__ == "__main__":
    main()
'''

README = """# ExMigrate scripts

Source workbook: {source}
Target: {dialect}

1. Create the tables: run `schema.sql` on the target database.
2. Load the data: `python load.py "<workbook>" --dialect {dialect} --url "<connection>"` (see the header of load.py).
3. `mapping.json` lists which sheet and column feed each table; edit it if the workbook layout changes.

FDE Toolbox does not connect to the target database; run these scripts where the database is reachable.
"""


def scripts_zip(erd: Erd, dialect: Dialect, source: str) -> bytes:
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("schema.sql", ddl(erd, dialect, source))
        zf.writestr("mapping.json", json.dumps(mapping(erd, source), ensure_ascii=False, indent=2))
        zf.writestr("load.py", LOAD_SCRIPT)
        zf.writestr("README.md", README.format(source=" ".join(source.split()), dialect=dialect))
    return buf.getvalue()
