"""onto_concepts

Revision ID: 0011
Revises: 0010
Create Date: 2026-10-09 02:40:23.664715
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "0011"
down_revision: str | None = "0010"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "onto_concepts",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("definition", sa.Text(), nullable=True),
        sa.Column("parent_ref", sa.JSON(), nullable=True),
        sa.Column("parent_concept_id", sa.String(length=36), nullable=True),
        sa.Column("id_attribute_id", sa.String(length=36), nullable=True),
        sa.Column("owner_dept", sa.String(length=100), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_concept_id"],
            ["onto_concepts.id"],
            name=op.f("fk_onto_concepts_parent_concept_id_onto_concepts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_onto_concepts_tenant_id_tenants"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_onto_concepts")),
    )
    with op.batch_alter_table("onto_concepts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_onto_concepts_parent_concept_id"), ["parent_concept_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_onto_concepts_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_onto_concepts_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "onto_attributes",
        sa.Column("concept_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("data_type", sa.String(length=20), nullable=False),
        sa.Column("unit", sa.String(length=50), nullable=True),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column("constraints", sa.JSON(), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(
            ["concept_id"],
            ["onto_concepts.id"],
            name=op.f("fk_onto_attributes_concept_id_onto_concepts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_onto_attributes_tenant_id_tenants"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_onto_attributes")),
    )
    with op.batch_alter_table("onto_attributes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_onto_attributes_concept_id"), ["concept_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_onto_attributes_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "onto_relations",
        sa.Column("source_concept_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("target_concept_id", sa.String(length=36), nullable=False),
        sa.Column("cardinality", sa.String(length=10), nullable=False),
        sa.Column("inverse_name", sa.String(length=200), nullable=True),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_concept_id"],
            ["onto_concepts.id"],
            name=op.f("fk_onto_relations_source_concept_id_onto_concepts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["target_concept_id"],
            ["onto_concepts.id"],
            name=op.f("fk_onto_relations_target_concept_id_onto_concepts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_onto_relations_tenant_id_tenants"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_onto_relations")),
    )
    with op.batch_alter_table("onto_relations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_onto_relations_source_concept_id"), ["source_concept_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_onto_relations_target_concept_id"), ["target_concept_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_onto_relations_tenant_id"), ["tenant_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("onto_relations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_onto_relations_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_onto_relations_target_concept_id"))
        batch_op.drop_index(batch_op.f("ix_onto_relations_source_concept_id"))

    op.drop_table("onto_relations")
    with op.batch_alter_table("onto_attributes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_onto_attributes_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_onto_attributes_concept_id"))

    op.drop_table("onto_attributes")
    with op.batch_alter_table("onto_concepts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_onto_concepts_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_onto_concepts_status"))
        batch_op.drop_index(batch_op.f("ix_onto_concepts_parent_concept_id"))

    op.drop_table("onto_concepts")
    # ### end Alembic commands ###
