"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-30 12:16:53.453569
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_eval_cases',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('input', sa.Text(), nullable=False),
    sa.Column('expected', sa.Text(), nullable=False),
    sa.Column('criteria', sa.Text(), nullable=True),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_eval_cases'))
    )
    with op.batch_alter_table('agent_eval_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_eval_cases_asset_id'), ['asset_id'], unique=False)

    op.create_table('asset_items',
    sa.Column('asset_type', sa.String(length=30), nullable=False),
    sa.Column('asset_key', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('change_note', sa.Text(), nullable=True),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_items')),
    sa.UniqueConstraint('asset_id', 'version', name='uq_asset_items_asset_version')
    )
    with op.batch_alter_table('asset_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_items_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_items_asset_key'), ['asset_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_items_asset_type'), ['asset_type'], unique=False)

    op.create_table('tenants',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('deployment_mode', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants')),
    sa.UniqueConstraint('code', name=op.f('uq_tenants_code'))
    )
    op.create_table('agent_eval_runs',
    sa.Column('template_ref', sa.JSON(), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('results', sa.JSON(), nullable=False),
    sa.Column('evidence_file_ids', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_agent_eval_runs_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_eval_runs'))
    )
    with op.batch_alter_table('agent_eval_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_eval_runs_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.String(length=36), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_audit_logs_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_at'), ['at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('engagements',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('lead_fde_id', sa.String(length=36), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_engagements_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_engagements'))
    )
    with op.batch_alter_table('engagements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_engagements_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('files',
    sa.Column('owner_type', sa.String(length=50), nullable=True),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('mime', sa.String(length=100), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_files_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_files'))
    )
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_files_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('systems',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('owner_dept', sa.String(length=100), nullable=True),
    sa.Column('hosting', sa.String(length=20), nullable=True),
    sa.Column('db_type', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_systems_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_systems'))
    )
    with op.batch_alter_table('systems', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_systems_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('users',
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('home_tenant_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['home_tenant_id'], ['tenants.id'], name=op.f('fk_users_home_tenant_id_tenants'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('agent_instances',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('template_ref', sa.JSON(), nullable=False),
    sa.Column('engagement_id', sa.String(length=36), nullable=False),
    sa.Column('deployment', sa.String(length=20), nullable=False),
    sa.Column('system_ids', sa.JSON(), nullable=False),
    sa.Column('overrides', sa.JSON(), nullable=False),
    sa.Column('concept_bindings', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('dev_project_id', sa.String(length=36), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], name=op.f('fk_agent_instances_engagement_id_engagements'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_agent_instances_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_instances'))
    )
    with op.batch_alter_table('agent_instances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_instances_engagement_id'), ['engagement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_instances_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('dev_projects',
    sa.Column('engagement_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('stack', sa.String(length=300), nullable=True),
    sa.Column('repo_url', sa.String(length=500), nullable=True),
    sa.Column('env_notes', sa.Text(), nullable=True),
    sa.Column('deploy_notes', sa.Text(), nullable=True),
    sa.Column('spec_document_ids', sa.JSON(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], name=op.f('fk_dev_projects_engagement_id_engagements'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_dev_projects_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dev_projects'))
    )
    with op.batch_alter_table('dev_projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dev_projects_engagement_id'), ['engagement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dev_projects_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('user_tenant_assignments',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_user_tenant_assignments_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_tenant_assignments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_tenant_assignments')),
    sa.UniqueConstraint('user_id', 'tenant_id', name='uq_user_tenant')
    )
    with op.batch_alter_table('user_tenant_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_tenant_assignments_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_tenant_assignments_user_id'), ['user_id'], unique=False)

    op.create_table('dev_tasks',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('assignee_id', sa.String(length=36), nullable=True),
    sa.Column('due', sa.Date(), nullable=True),
    sa.Column('pause_note', sa.Text(), nullable=True),
    sa.Column('resume_note', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['dev_projects.id'], name=op.f('fk_dev_tasks_project_id_dev_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_dev_tasks_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dev_tasks'))
    )
    with op.batch_alter_table('dev_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dev_tasks_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dev_tasks_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('dev_prompts',
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('tool', sa.String(length=50), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['dev_tasks.id'], name=op.f('fk_dev_prompts_task_id_dev_tasks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_dev_prompts_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dev_prompts'))
    )
    with op.batch_alter_table('dev_prompts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dev_prompts_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dev_prompts_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dev_prompts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dev_prompts_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_dev_prompts_task_id'))

    op.drop_table('dev_prompts')
    with op.batch_alter_table('dev_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dev_tasks_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_dev_tasks_project_id'))

    op.drop_table('dev_tasks')
    with op.batch_alter_table('user_tenant_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_tenant_assignments_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_tenant_assignments_tenant_id'))

    op.drop_table('user_tenant_assignments')
    with op.batch_alter_table('dev_projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dev_projects_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_dev_projects_engagement_id'))

    op.drop_table('dev_projects')
    with op.batch_alter_table('agent_instances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_instances_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_agent_instances_engagement_id'))

    op.drop_table('agent_instances')
    op.drop_table('users')
    with op.batch_alter_table('systems', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_systems_tenant_id'))

    op.drop_table('systems')
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_files_tenant_id'))

    op.drop_table('files')
    with op.batch_alter_table('engagements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_engagements_tenant_id'))

    op.drop_table('engagements')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_at'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('agent_eval_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_eval_runs_tenant_id'))

    op.drop_table('agent_eval_runs')
    op.drop_table('tenants')
    with op.batch_alter_table('asset_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_items_asset_type'))
        batch_op.drop_index(batch_op.f('ix_asset_items_asset_key'))
        batch_op.drop_index(batch_op.f('ix_asset_items_asset_id'))

    op.drop_table('asset_items')
    with op.batch_alter_table('agent_eval_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_eval_cases_asset_id'))

    op.drop_table('agent_eval_cases')
    # ### end Alembic commands ###
