"""onto_mappings

Revision ID: 0012
Revises: 0011
Create Date: 2026-10-09 03:41:41.262119
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "0012"
down_revision: str | None = "0011"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "onto_mappings",
        sa.Column("target_kind", sa.String(length=20), nullable=False),
        sa.Column("target_id", sa.String(length=36), nullable=False),
        sa.Column("concept_id", sa.String(length=36), nullable=False),
        sa.Column("system_id", sa.String(length=36), nullable=True),
        sa.Column("table_name", sa.String(length=200), nullable=True),
        sa.Column("column_name", sa.String(length=200), nullable=True),
        sa.Column("interface_id", sa.String(length=36), nullable=True),
        sa.Column("origin", sa.String(length=20), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(
            ["concept_id"],
            ["onto_concepts.id"],
            name=op.f("fk_onto_mappings_concept_id_onto_concepts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["interface_id"],
            ["interfaces.id"],
            name=op.f("fk_onto_mappings_interface_id_interfaces"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["system_id"], ["systems.id"], name=op.f("fk_onto_mappings_system_id_systems"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_onto_mappings_tenant_id_tenants"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_onto_mappings")),
    )
    with op.batch_alter_table("onto_mappings", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_onto_mappings_concept_id"), ["concept_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_onto_mappings_interface_id"), ["interface_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_onto_mappings_system_id"), ["system_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_onto_mappings_target_id"), ["target_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_onto_mappings_tenant_id"), ["tenant_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("onto_mappings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_onto_mappings_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_onto_mappings_target_id"))
        batch_op.drop_index(batch_op.f("ix_onto_mappings_system_id"))
        batch_op.drop_index(batch_op.f("ix_onto_mappings_interface_id"))
        batch_op.drop_index(batch_op.f("ix_onto_mappings_concept_id"))

    op.drop_table("onto_mappings")
    # ### end Alembic commands ###
