"""dev_issues

Revision ID: 0010
Revises: 0009
Create Date: 2026-10-09 02:18:52.797826
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0010"
down_revision: str | None = "0009"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dev_issues",
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("priority", sa.String(length=20), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("source", sa.JSON(), nullable=True),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"], ["dev_projects.id"], name=op.f("fk_dev_issues_project_id_dev_projects"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_dev_issues_tenant_id_tenants"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dev_issues")),
    )
    with op.batch_alter_table("dev_issues", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_dev_issues_project_id"), ["project_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_dev_issues_tenant_id"), ["tenant_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dev_issues", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_dev_issues_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_dev_issues_project_id"))

    op.drop_table("dev_issues")
    # ### end Alembic commands ###
