"""ontomap

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-01 05:32:53.876636
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0004'
down_revision: str | None = '0003'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onto_candidates',
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolved_into_id', sa.String(length=36), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_onto_candidates_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_onto_candidates')),
    sa.UniqueConstraint('tenant_id', 'kind', 'source_type', 'source_id', 'name', name='uq_onto_candidates_tenant_source_name')
    )
    with op.batch_alter_table('onto_candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_onto_candidates_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_onto_candidates_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_onto_candidates_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('onto_terms',
    sa.Column('term', sa.String(length=200), nullable=False),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('abbreviation', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('concept_id', sa.String(length=36), nullable=True),
    sa.Column('source_type', sa.String(length=30), nullable=True),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_onto_terms_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_onto_terms')),
    sa.UniqueConstraint('tenant_id', 'term', name='uq_onto_terms_tenant_term')
    )
    with op.batch_alter_table('onto_terms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_onto_terms_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_onto_terms_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('onto_term_aliases',
    sa.Column('term_id', sa.String(length=36), nullable=False),
    sa.Column('alias', sa.String(length=200), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_onto_term_aliases_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_id'], ['onto_terms.id'], name=op.f('fk_onto_term_aliases_term_id_onto_terms'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_onto_term_aliases'))
    )
    with op.batch_alter_table('onto_term_aliases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_onto_term_aliases_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_onto_term_aliases_term_id'), ['term_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('onto_term_aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_onto_term_aliases_term_id'))
        batch_op.drop_index(batch_op.f('ix_onto_term_aliases_tenant_id'))

    op.drop_table('onto_term_aliases')
    with op.batch_alter_table('onto_terms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_onto_terms_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_onto_terms_status'))

    op.drop_table('onto_terms')
    with op.batch_alter_table('onto_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_onto_candidates_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_onto_candidates_status'))
        batch_op.drop_index(batch_op.f('ix_onto_candidates_source_id'))

    op.drop_table('onto_candidates')
    # ### end Alembic commands ###
