"""exmigrate

Revision ID: 0008
Revises: 0007
Create Date: 2026-10-08 13:12:56.488604
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0008'
down_revision: str | None = '0007'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('xl_analyses',
    sa.Column('engagement_id', sa.String(length=36), nullable=False),
    sa.Column('file_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('report', sa.JSON(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], name=op.f('fk_xl_analyses_engagement_id_engagements'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name=op.f('fk_xl_analyses_file_id_files'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_xl_analyses_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_xl_analyses'))
    )
    with op.batch_alter_table('xl_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_xl_analyses_engagement_id'), ['engagement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_xl_analyses_file_id'), ['file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_xl_analyses_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('xl_erd_drafts',
    sa.Column('analysis_id', sa.String(length=36), nullable=False),
    sa.Column('erd', sa.JSON(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_by', sa.String(length=36), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['xl_analyses.id'], name=op.f('fk_xl_erd_drafts_analysis_id_xl_analyses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_xl_erd_drafts_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_xl_erd_drafts')),
    sa.UniqueConstraint('tenant_id', 'analysis_id', name='uq_xl_erd_drafts_tenant_analysis')
    )
    with op.batch_alter_table('xl_erd_drafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_xl_erd_drafts_analysis_id'), ['analysis_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_xl_erd_drafts_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('xl_erd_drafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_xl_erd_drafts_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_xl_erd_drafts_analysis_id'))

    op.drop_table('xl_erd_drafts')
    with op.batch_alter_table('xl_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_xl_analyses_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_xl_analyses_file_id'))
        batch_op.drop_index(batch_op.f('ix_xl_analyses_engagement_id'))

    op.drop_table('xl_analyses')
    # ### end Alembic commands ###
