"""specforge

Revision ID: 0009
Revises: 0007
Create Date: 2026-10-08 15:06:14.280431
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0009'
down_revision: str | None = '0007'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spec_documents',
    sa.Column('engagement_id', sa.String(length=36), nullable=False),
    sa.Column('doc_type', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('template_ref', sa.JSON(), nullable=True),
    sa.Column('rule_pack_refs', sa.JSON(), nullable=False),
    sa.Column('source_refs', sa.JSON(), nullable=False),
    sa.Column('content_md', sa.Text(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], name=op.f('fk_spec_documents_engagement_id_engagements'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_spec_documents_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_spec_documents'))
    )
    with op.batch_alter_table('spec_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spec_documents_engagement_id'), ['engagement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_spec_documents_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('spec_versions',
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content_md', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['spec_documents.id'], name=op.f('fk_spec_versions_document_id_spec_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_spec_versions_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_spec_versions')),
    sa.UniqueConstraint('tenant_id', 'document_id', 'version', name='uq_spec_versions_doc_version')
    )
    with op.batch_alter_table('spec_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spec_versions_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_spec_versions_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spec_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spec_versions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_spec_versions_document_id'))

    op.drop_table('spec_versions')
    with op.batch_alter_table('spec_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spec_documents_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_spec_documents_engagement_id'))

    op.drop_table('spec_documents')
    # ### end Alembic commands ###
