"""interfaces

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-01 01:24:12.451735
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "interface_uploads",
        sa.Column("file_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("result", sa.JSON(), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(
            ["file_id"], ["files.id"], name=op.f("fk_interface_uploads_file_id_files"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_interface_uploads_tenant_id_tenants"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_interface_uploads")),
    )
    with op.batch_alter_table("interface_uploads", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_interface_uploads_file_id"), ["file_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_interface_uploads_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "interfaces",
        sa.Column("if_code", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("source_system_id", sa.String(length=36), nullable=False),
        sa.Column("target_system_id", sa.String(length=36), nullable=False),
        sa.Column("link_type", sa.String(length=20), nullable=False),
        sa.Column("schedule", sa.String(length=100), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("daily_volume", sa.Integer(), nullable=True),
        sa.Column("owner", sa.String(length=100), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_system_id"], ["systems.id"], name=op.f("fk_interfaces_source_system_id_systems")
        ),
        sa.ForeignKeyConstraint(
            ["target_system_id"], ["systems.id"], name=op.f("fk_interfaces_target_system_id_systems")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_interfaces_tenant_id_tenants"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_interfaces")),
        sa.UniqueConstraint("tenant_id", "if_code", name="uq_interfaces_tenant_if_code"),
    )
    with op.batch_alter_table("interfaces", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_interfaces_source_system_id"), ["source_system_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_interfaces_target_system_id"), ["target_system_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_interfaces_tenant_id"), ["tenant_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("interfaces", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_interfaces_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_interfaces_target_system_id"))
        batch_op.drop_index(batch_op.f("ix_interfaces_source_system_id"))

    op.drop_table("interfaces")
    with op.batch_alter_table("interface_uploads", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_interface_uploads_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_interface_uploads_file_id"))

    op.drop_table("interface_uploads")
    # ### end Alembic commands ###
