"""flowdesk

Revision ID: 0007
Revises: 0006
Create Date: 2026-10-08 08:54:27.666403
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0007'
down_revision: str | None = '0006'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flows',
    sa.Column('engagement_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('pair_id', sa.String(length=36), nullable=True),
    sa.Column('perspective', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('template_ref', sa.JSON(), nullable=True),
    sa.Column('graph', sa.JSON(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], name=op.f('fk_flows_engagement_id_engagements'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_flows_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_flows'))
    )
    with op.batch_alter_table('flows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flows_engagement_id'), ['engagement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_flows_pair_id'), ['pair_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_flows_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('flow_snapshots',
    sa.Column('flow_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('graph', sa.JSON(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['flow_id'], ['flows.id'], name=op.f('fk_flow_snapshots_flow_id_flows'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_flow_snapshots_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_flow_snapshots'))
    )
    with op.batch_alter_table('flow_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flow_snapshots_flow_id'), ['flow_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_flow_snapshots_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flow_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flow_snapshots_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_flow_snapshots_flow_id'))

    op.drop_table('flow_snapshots')
    with op.batch_alter_table('flows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flows_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_flows_pair_id'))
        batch_op.drop_index(batch_op.f('ix_flows_engagement_id'))

    op.drop_table('flows')
    # ### end Alembic commands ###
