"""coachq

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-01 02:32:56.967753
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0003'
down_revision: str | None = '0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coach_custom_questions',
    sa.Column('engagement_id', sa.String(length=36), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('audience', sa.JSON(), nullable=False),
    sa.Column('follow_ups', sa.JSON(), nullable=False),
    sa.Column('source_ref', sa.JSON(), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], name=op.f('fk_coach_custom_questions_engagement_id_engagements'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_coach_custom_questions_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coach_custom_questions'))
    )
    with op.batch_alter_table('coach_custom_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coach_custom_questions_engagement_id'), ['engagement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coach_custom_questions_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('coach_subjects',
    sa.Column('engagement_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('job_title', sa.String(length=100), nullable=True),
    sa.Column('system_ids', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], name=op.f('fk_coach_subjects_engagement_id_engagements'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_coach_subjects_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coach_subjects'))
    )
    with op.batch_alter_table('coach_subjects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coach_subjects_engagement_id'), ['engagement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coach_subjects_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('coach_sessions',
    sa.Column('engagement_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], name=op.f('fk_coach_sessions_engagement_id_engagements'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['coach_subjects.id'], name=op.f('fk_coach_sessions_subject_id_coach_subjects'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_coach_sessions_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coach_sessions'))
    )
    with op.batch_alter_table('coach_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coach_sessions_engagement_id'), ['engagement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coach_sessions_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coach_sessions_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('coach_session_questions',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('question_ref', sa.JSON(), nullable=True),
    sa.Column('custom_question_id', sa.String(length=36), nullable=True),
    sa.Column('custom_text', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('follow_ups', sa.JSON(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['custom_question_id'], ['coach_custom_questions.id'], name=op.f('fk_coach_session_questions_custom_question_id_coach_custom_questions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['coach_sessions.id'], name=op.f('fk_coach_session_questions_session_id_coach_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_coach_session_questions_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coach_session_questions'))
    )
    with op.batch_alter_table('coach_session_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coach_session_questions_custom_question_id'), ['custom_question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coach_session_questions_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coach_session_questions_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('coach_insights',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('session_question_id', sa.String(length=36), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['coach_sessions.id'], name=op.f('fk_coach_insights_session_id_coach_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_question_id'], ['coach_session_questions.id'], name=op.f('fk_coach_insights_session_question_id_coach_session_questions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_coach_insights_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coach_insights'))
    )
    with op.batch_alter_table('coach_insights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coach_insights_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coach_insights_session_question_id'), ['session_question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coach_insights_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('coach_action_items',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('insight_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('assignee', sa.String(length=100), nullable=True),
    sa.Column('due', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['insight_id'], ['coach_insights.id'], name=op.f('fk_coach_action_items_insight_id_coach_insights'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['coach_sessions.id'], name=op.f('fk_coach_action_items_session_id_coach_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_coach_action_items_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coach_action_items'))
    )
    with op.batch_alter_table('coach_action_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coach_action_items_insight_id'), ['insight_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coach_action_items_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coach_action_items_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coach_action_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coach_action_items_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_coach_action_items_session_id'))
        batch_op.drop_index(batch_op.f('ix_coach_action_items_insight_id'))

    op.drop_table('coach_action_items')
    with op.batch_alter_table('coach_insights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coach_insights_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_coach_insights_session_question_id'))
        batch_op.drop_index(batch_op.f('ix_coach_insights_session_id'))

    op.drop_table('coach_insights')
    with op.batch_alter_table('coach_session_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coach_session_questions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_coach_session_questions_session_id'))
        batch_op.drop_index(batch_op.f('ix_coach_session_questions_custom_question_id'))

    op.drop_table('coach_session_questions')
    with op.batch_alter_table('coach_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coach_sessions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_coach_sessions_subject_id'))
        batch_op.drop_index(batch_op.f('ix_coach_sessions_engagement_id'))

    op.drop_table('coach_sessions')
    with op.batch_alter_table('coach_subjects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coach_subjects_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_coach_subjects_engagement_id'))

    op.drop_table('coach_subjects')
    with op.batch_alter_table('coach_custom_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coach_custom_questions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_coach_custom_questions_engagement_id'))

    op.drop_table('coach_custom_questions')
    # ### end Alembic commands ###
