"""adapters

Revision ID: 0006
Revises: 0005
Create Date: 2026-10-07 05:54:01.985727
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0006'
down_revision: str | None = '0005'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adapter_activations',
    sa.Column('adapter_key', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('credentials_encrypted', sa.Text(), nullable=True),
    sa.Column('egress_notice', sa.JSON(), nullable=False),
    sa.Column('request_note', sa.Text(), nullable=True),
    sa.Column('requested_by', sa.String(length=36), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approval_reason', sa.Text(), nullable=True),
    sa.Column('deactivated_by', sa.String(length=36), nullable=True),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_adapter_activations_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_adapter_activations')),
    sa.UniqueConstraint('tenant_id', 'adapter_key', name='uq_adapter_activations_tenant_key')
    )
    with op.batch_alter_table('adapter_activations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_adapter_activations_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adapter_activations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_adapter_activations_tenant_id'))

    op.drop_table('adapter_activations')
    # ### end Alembic commands ###
